#   _____ _       _____                    _                         _
#  / ____| |     / ____|                  | |                       | |
# | (___ | | __ | (___   ___ ___  _ __ ___| |__   ___   __ _ _ __ __| |
#  \___ \| |/ /  \___ \ / __/ _ \| '__/ _ \ '_ \ / _ \ / _` | '__/ _` |
#  ____) |   <   ____) | (_| (_) | | |  __/ |_) | (_) | (_| | | | (_| |
# |_____/|_|\_\ |_____/ \___\___/|_|  \___|_.__/ \___/ \__,_|_|  \__,_|
#
# Created by: MrUniverse44
# Version: 1.3
# Link: https://www.spigotmc.org/resources/80983/
settings:
  dateFormat: dd/MM/yy
  update-check: true
  extra-debug-messages: false
