package dev.mruniverse.pixelskscoreboard.conditions;

import ch.njol.skript.Skript;
import ch.njol.skript.lang.Condition;
import ch.njol.skript.lang.Expression;
import ch.njol.skript.lang.SkriptParser;
import ch.njol.util.Kleenean;
import dev.mruniverse.pixelskscoreboard.PixelSkScoreboard;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.event.Event;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.File;
import java.util.Objects;

@SuppressWarnings("unused")
public class CondTitleExists extends Condition {
    Expression<String> name;
    Expression<String> file;


    static {
        Skript.registerCondition(CondTitleExists.class, "(scoreboard|skscoreboard) title[ of board] named %string% (in|of) file %string% (1¦is|2¦is(n't| not)) created");
    }

    @SuppressWarnings({"unchecked"})
    public boolean init(Expression<?> @NotNull [] expressions, int matchedPattern, @NotNull Kleenean isDelayed, SkriptParser.ParseResult parser) {
        this.name = (Expression<String>)expressions[0];
        this.file = (Expression<String>)expressions[1];
        setNegated((parser.mark == 1));
        return true;
    }

    public @NotNull String toString(@Nullable Event event, boolean debug) {
        return "scoreboard title of board named " + name.toString(event,debug) + " in file " + file.toString(event,debug) + " isn't created";
    }

    @SuppressWarnings("SimplifiableConditionalExpression")
    public boolean check(@NotNull Event event) {
        PixelSkScoreboard board = PixelSkScoreboard.getControl();
        try {
            File configFile = board.getStorage().getExternalFile(Objects.requireNonNull(file.getSingle(event)));
            FileConfiguration configuration = board.getStorage().loadExternalConfigWithFile(configFile);
            return configuration.contains("scoreboards." + name.getSingle(event) + ".title") ? isNegated() : (!isNegated());
        }catch (Throwable throwable) {
            board.getLogs().error("Can't check condition, Error generated by an script in this server!");
            board.getLogs().error(throwable);
        }
        return false;
    }
}
